{
  "kind": "Deployment",
  "apiVersion": "extensions/v1beta1",
  "metadata": {
    "name": "rpy-node",
    "namespace": "default",
    "selfLink": "/apis/extensions/v1beta1/namespaces/default/deployments/rpy-node",
    "uid": "ab5bd444-4ede-11e9-8d01-080027003269",
    "resourceVersion": "21113",
    "generation": 1,
    "creationTimestamp": "2019-03-25T09:16:27Z",
    "labels": {
      "run": "rpy-node"
    },
    "annotations": {
      "deployment.kubernetes.io/revision": "1"
    }
  },
  "spec": {
    "replicas": 1,
    "selector": {
      "matchLabels": {
        "run": "rpy-node"
      }
    },
    "template": {
      "metadata": {
        "creationTimestamp": null,
        "labels": {
          "run": "rpy-node"
        }
      },
      "spec": {
        "containers": [
          {
            "name": "rpy-node",
            "image": "mozartua/rpy:latest",
            "ports": [
              {
                "containerPort": 80,
                "protocol": "TCP"
              }
            ],
            "resources": {},
            "terminationMessagePath": "/dev/termination-log",
            "terminationMessagePolicy": "File",
            "imagePullPolicy": "Always"
          }
        ],
        "restartPolicy": "Always",
        "terminationGracePeriodSeconds": 30,
        "dnsPolicy": "ClusterFirst",
        "securityContext": {},
        "schedulerName": "default-scheduler"
      }
    },
    "strategy": {
      "type": "RollingUpdate",
      "rollingUpdate": {
        "maxUnavailable": "25%",
        "maxSurge": "25%"
      }
    },
    "revisionHistoryLimit": 10,
    "progressDeadlineSeconds": 600
  },
  "status": {
    "observedGeneration": 1,
    "replicas": 1,
    "updatedReplicas": 1,
    "readyReplicas": 1,
    "availableReplicas": 1,
    "conditions": [
      {
        "type": "Available",
        "status": "True",
        "lastUpdateTime": "2019-03-25T09:16:32Z",
        "lastTransitionTime": "2019-03-25T09:16:32Z",
        "reason": "MinimumReplicasAvailable",
        "message": "Deployment has minimum availability."
      },
      {
        "type": "Progressing",
        "status": "True",
        "lastUpdateTime": "2019-03-25T09:16:32Z",
        "lastTransitionTime": "2019-03-25T09:16:27Z",
        "reason": "NewReplicaSetAvailable",
        "message": "ReplicaSet \"rpy-node-7845c6b948\" has successfully progressed."
      }
    ]
  }
}